# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: red_space_development

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "red_space_test") %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgres") %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    database: red_space_production
    username: red_space
    password: <%= ENV["RED_SPACE_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: red_space_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: red_space_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: red_space_production_cable
    migrations_paths: db/cable_migrate
